[package]
name = "main_lib"
version = "0.1.0"
authors = ["Itstunner <ahmedfawad928@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
table = {path = "../table"}